In [1]:
import numpy as np

In [3]:
# User Defined Input

# Example Input
A = np.array([[-2, 1, 1, 0, 0],
             [-1, 2, 0, 1, 0],
             [1, 0, 0, 0, 1]])

b = np.array([2, 7, 3])

c = np.array([-1, -2, 0, 0, 0])


In [223]:
# Q1
A = np.array([[-2, -2,  3,  4, -2],
              [ 1,  4,  1, -1, -1]])

bT = np.array([ 0,  7])

cT = np.array([-2,  7, 14,  2, -4])

basicInd= np.array([0,2]) #x1 and x3 have indices 0 and 2

In [220]:
xhat @ cbT

-56.0

In [226]:
def primal_simplex(A,bT,cT,basicInd):
    basicSize = A.shape[0] # number of constraints, m, 2
    nonbasicSize = A.shape[1] - basicSize #n-m, number of variables, 3
    n = basicSize
    m = nonbasicSize
    no_iter = 0
    nonbasicInd = np.delete(np.arange(n+m),basicInd)
    
#     x_b = np.linalg.inv(Ab) @ bT
    
    while True:
        no_iter += 1
        print(no_iter)
        print("basicInd",basicInd)
        print("nonbasicInd",nonbasicInd)

        #step 1
        cbT = np.array(cT[basicInd]) #basic variable cost coefficients
#         print("cbT: ",cbT)
        cnbT = np.array(cT[nonbasicInd]) #basic variable cost coefficients
#         print("cnbT: ",cnbT)

        Ab = A[:,basicInd] #basis matrix
        An = A[:,nonbasicInd] #nonbasic variable matrix
        
        print("Ab",Ab)
        print("An",An)
        Abinv = np.linalg.inv(Ab)
        
        
        xhat = Abinv @ bT
        print("xhat",xhat)
        #dual variables
        yT = cbT @ Abinv

        #step 2: reduced costs
        dN = cnbT - N.T @ yT

        #step 3, current basis is optimal and can return answer
        if(all(i>=0 for i in dN)):
            xhat = Abinv @ bT
            
            return True, basicInd, no_iter, xhat, xhat @ cbT

        #step 4
        dNMinIndx = np.argmin(dN)
        print("nonbasicInd",nonbasicInd)
        j = nonbasicInd[dNMinIndx] #entering variable
        print("entering",j)

        #step 6
        yhat = Abinv @ A[:, j]

        #step 7: return unbounded solution
        if(all(i<=0 for i in yhat)):
            return False, None, None, None, None

        #step 9: yi = yhat, xi = Binv @ bT 
        xhat = Abinv @ bT
        theta = xhat/yhat
        
        
        print("xhat", xhat)
        print("theta",theta)
        print("basicInd",basicInd)
        minimum_value = float('inf')
        minIndex = 0
        for i in range(len(yhat)):
            if yhat[i]>0:
                if xhat[i]/yhat[i]<=minimum_value:
                    minimum_value = xhat[i]/yhat[i]
                    minIndex = i
        
        theta_star = minimum_value
        l = basicInd[minIndex]
#         l = basicInd[np.argmin(theta)] # leaving variable
        print("leaving",l)

        
        #step 10        
#         x_b = x_b - theta_star * yhat

        basicInd = np.append(basicInd[basicInd!=l],j)

        nonbasicInd = np.append(nonbasicInd[nonbasicInd!=j],l)

        #step 11,12
        Ab = A[:,basicInd] #basis matrix
        An = A[:,nonbasicInd] #nonbasic variable matrix

        #step 13

In [227]:
boolean, basisInd, no_iter, xhat, answer = primal_simplex(A,bT,cT,basis)
print("basis:",basisInd)
print("xhat:",xhat)
print("answer:",answer)

1
basicInd [0 2]
nonbasicInd [1 3 4]
Ab [[-2  3]
 [ 1  1]]
An [[-2  4 -2]
 [ 4 -1 -1]]
xhat [4.2 2.8]
nonbasicInd [1 3 4]
entering 3
xhat [4.2 2.8]
theta [-3.  7.]
basicInd [0 2]
leaving 2
2
basicInd [0 3]
nonbasicInd [1 4 2]
Ab [[-2  4]
 [ 1 -1]]
An [[-2 -2  3]
 [ 4 -1  1]]
xhat [14.  7.]
nonbasicInd [1 4 2]
entering 4
basis: None
xhat: None
answer: None


In [195]:
theta

array([-3.,  7.])

In [156]:
basicSize = A.shape[0] # number of constraints, m, 2
nonbasicSize = A.shape[1] - basicSize #n-m, number of variables, 3
n = basicSize
m = nonbasicSize


nonbasicInd = np.delete(np.arange(n+m),basicInd)

#step 1
cbT = np.array(cT[basicInd]) #basic variable cost coefficients
cnbT = np.array(cT[nonbasicInd]) #basic variable cost coefficients

Ab = A[:,basicInd] #basis matrix
An = A[:,nonbasicInd] #nonbasic variable matrix
Abinv = np.linalg.inv(Ab)
#dual variables
yT = cbT @ Abinv

#step 2: reduced costs
dN = cnbT - N.T @ yT

#step 3, current basis is optimal and can return answer
# if(all(i>=0 for i in dN)):
#     return True, basisInd

#step 4
dNMinIndx = np.argmin(dN)
j = nonbasicInd[dNMinIndx] #entering variable

#step 6
yhat = Abinv @ A[:, j]

#step 7: return unbounded solution
# if(all(i<=0 for i in yhat)):
#     return False, None, None

#step 9: yi = yhat, xi = Binv @ bT 
xhat = Abinv @ bT
theta = xhat/yhat
l = np.argmin(theta) # leaving variable
theta_star = min(theta)


basicInd = np.append(basicInd[basicInd!=l],j)

nonbasicInd = np.append(nonbasicInd[nonbasicInd!=j],l)

#step 11,12
Ab = A[:,basicInd] #basis matrix
An = A[:,nonbasicInd] #nonbasic variable matrix

#step 13




In [157]:
l

0

In [158]:
j

3

In [159]:
basicInd

array([2, 3])

In [160]:
nonbasicInd

array([1, 4, 0], dtype=int64)

In [ ]:
np.delete(basicInd,)

In [8]:
np.argmin(c)

4

In [10]:
np.min??

In [19]:
def Simplex(A, b, c):
    '''Takes input vars, computs corresponding values,
    then uses while loop to iterate until a basic optimal solution is reached.
    RETURNS: cbT, cbIndx, cnT, cnIndx, bHat, cnHat.
    cbT, cbIndex is final basic variable values, and indices
    cnT, cnIndex is final nonbasic variable values and indices
    bHat is final solution values, 
    cnHat is optimality condition'''
    
    #sizes of basic and nonbasic vectors
    basicSize = A.shape[0] # number of constraints, m
    nonbasicSize = A.shape[1] - basicSize #n-m, number of variables
        
    # global index tracker of variables of basic and nonbasic variables (objective)
    # that is, index 0 corresponds with x_0, 1 with x_1 and so on.  So each index corresponds with a variable
    cindx = [i for i in range(0, len(c))]
    
    #basic variable coefficients
    cbT = np.array(c[nonbasicSize:])

    #nonbasic variable coefficients
    cnT = np.array(c[:nonbasicSize])
    
    # run core simplex method until reach the optimal solution
    while True:
        
        # keep track of current indices of basic and non-basic variables
        cbIndx = cindx[nonbasicSize:]
        cnIndx = cindx[:nonbasicSize]
        
        # basis matrix
        B = A[:, cbIndx]
        Binv = np.linalg.inv(B)
        
        # nonbasic variable matrix
        N = A[:, cnIndx]
        
        # bHat, the values of the basic variables
        # recall that at the start the basic variables are the slack variables, and 
        # have values equal the vector b (as primary variables are set to 0 at the start)
        bHat = Binv @ b
        yT = cbT @ Binv
        
        # use to check for optimality, determine variable to enter basis
        cnHat = cnT - (yT @ N)
        
        # break out of loop, returning values if all values of cnhat are above 0
        if(all(i>=0 for i in cnHat)):
            # use cbIndx to get index values of variables in bHat, and the corresponding index
            # values in bHat are the final solution values for each of the corresponding variables
            # ie value 0 in dbIndx corresponds with first variable, so whatever the index for the 0 is
            # is the index in bHat that has the solution value for that variable.
            return cbT, cbIndx, cnT, cnIndx, bHat, cnHat
        
        
        # find indx of minimum value of cnhat, this is the variable to enter the basis
        cnMinIndx = np.argmin(cnHat)
        
        # this is the index for the column of coeffs in a for the given variable
        indx = cindx[cnMinIndx]

        Ahat = Binv @ A[:, indx]
        
        # now we want to iterate through Ahat and bHat and pick the minimum ratios
        # only take ratios of variables with Ahat_i values greater than 0
        # pick smallest ratio to get variable that will become nonbasic.
        ratios = []
        for i in range(0, len(bHat)):
            Aval = Ahat[i]
            Bval = bHat[i]

            # don't look at ratios with val less then or eqaul to 0, append to keep index
            if(Aval <= 0):
                ratios.append(10000000)
                continue
            ratios.append(Bval / Aval)

        ratioMinIndx = np.argmin(ratios)

        #switch basic and nonbasic variables using the indices.
        cnT[cnMinIndx], cbT[ratioMinIndx] = cbT[ratioMinIndx], cnT[cnMinIndx]
        # switch global index tracker indices
        cindx[cnMinIndx], cindx[ratioMinIndx + nonbasicSize] = cindx[ratioMinIndx + nonbasicSize], cindx[cnMinIndx]
        # now repeat the loop
        

Simplex(A, b, c)

(array([-2, -1,  0]),
 [1, 0, 2],
 array([0, 0]),
 [3, 4],
 array([5., 3., 3.]),
 array([1., 2.]))