In [106]:
import numpy as np

In [107]:
# Q1
A = np.array([[-2, -2,  3,  1, -2],
              [ 1,  4,  1, -1, -1]])

bT = np.array([ 0,  7])

cT = np.array([-2,  7, 14,  2, -4])

basicInd= np.array([3,4]) #x1 and x3 have indices 0 and 2

In [108]:
def primal_simplex(A,bT,cT,basicInd):
    basicSize = A.shape[0] # number of constraints, m, 2
    nonbasicSize = A.shape[1] - basicSize #n-m, number of variables, 3
    n = basicSize
    m = nonbasicSize
    no_iter = 0
    nonbasicInd = np.delete(np.arange(n+m), basicInd)
    
#     x_b = np.linalg.inv(Ab) @ bT
    
    while True:
        print()
        print ("start of iter "+str(no_iter)+", basis is :",basicInd)
        no_iter += 1

        #step 1
        cbT = np.array(cT[basicInd]) #basic variable cost coefficients
        cnbT = np.array(cT[nonbasicInd]) #basic variable cost coefficients
        print("cbT: ",cbT)
        print("cnbT: ",cnbT)

        Ab = np.copy(A[:,basicInd]) #basis matrix
        An = np.copy(A[:,nonbasicInd]) #nonbasic variable matrix
        print("Ab:",Ab)
        print("An:",An)
        

        Abinv = np.linalg.inv(Ab)
        
        
        xhat = Abinv @ bT
        print ('1xhat',xhat)
        #dual variables
        pi = cbT @ Abinv
        print("pi",pi)

        #step 2: reduced costs
        dN = cnbT - An.T @ pi
        print ("dN IN STEP2",dN)

        #step 3, current basis is optimal and can return answer
        if(all(i>=0 for i in dN)):
            xhat = Abinv @ bT
            
            return True, basicInd, no_iter, xhat, xhat @ cbT

        #step 4
        
        print('index of negative value',np.where(dN < 0))
        
        #dNMinIndx = np.argmin(dN)
        
        dNMinIndx=np.where(dN < 0)[0][0]
        
#         print ("dN",dN)
#         print ('dNMinIndx',dNMinIndx)
        
#         print ('basicInd',basicInd)
#         print ('nonbasic',nonbasicInd)
        
        j = nonbasicInd[dNMinIndx] #entering variable
#         print ('j',j)

        #step 6
        yhat = Abinv @ A[:, j]

        #step 7: return unbounded solution
        if(all(i<=0 for i in yhat)):
            return False, None, None, None, None

        #step 9: yi = yhat, xi = Binv @ bT 
        xhat = Abinv @ bT
#         print ('2xhat',xhat)
        theta = xhat/yhat
        
        minimum_value = float('inf')
        minIndex = 0
        for i in range(len(yhat)):
            if yhat[i]>0:
                if xhat[i]/yhat[i]<=minimum_value:
                    minimum_value = xhat[i]/yhat[i]
                    minIndex = i
        
        theta_star = minimum_value
        l = basicInd[minIndex]
#         l = basicInd[np.argmin(theta)] # leaving variable
#         print("leaving",l)
        
        basicInd = np.append(basicInd[basicInd!=l],j)

        nonbasicInd = np.append(nonbasicInd[nonbasicInd!=j],l)
        nonbasicInd=np.sort(nonbasicInd)


        #step 11,12
        Ab = np.copy(A[:,basicInd]) #basis matrix
        An = np.copy(A[:,nonbasicInd]) #nonbasic variable matrix

        #step 13

In [109]:
boolean, basisInd, no_iter, xhat, answer = primal_simplex(A,bT,cT,basicInd)
print("basis:",basisInd)
print("xhat:",xhat)
print("answer:",answer)


start of iter 0, basis is : [3 4]
cbT:  [ 2 -4]
cnbT:  [-2  7 14]
Ab: [[ 1 -2]
 [-1 -1]]
An: [[-2 -2  3]
 [ 1  4  1]]
1xhat [-4.66666667 -2.33333333]
pi [2. 0.]
dN IN STEP2 [ 2. 11.  8.]
basis: [3 4]
xhat: [-4.66666667 -2.33333333]
answer: 0.0


In [43]:
test = np.array([[1,2,3,4],])
print(test)
print(test.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


1

In [35]:
A_B = np.copy(A[:,[1,2]])
A_N = np.copy(A[:,[0,3,4]])
pi = np.linalg.inv(A_B.T)@ cT[[1,2]]
print(pi)
print(c[[0,3,4]] - A_N.T @ pi)

[3.5 3.5]
[  2.5 -10.5  10.5]
