In [1]:
import numpy as np
import pandas as pd
from scipy.stats import binom

In [2]:
A = np.array([[40, 32, 3],
             [65, 19, 8],
             [100,10,4]])
B = np.array([[32,8,0],
             [64,16,0],
             [128,0,2]])

In [4]:
A = pd.read_clipboard()

In [9]:
B = np.array(A)

(7, 7)

In [13]:
ctr = 0
for r in range(7):
    curr = 0
    for c in range(7):
        if curr != B[r,c]:
            ctr += 1
            curr = B[r,c]
print(ctr)

25


In [17]:
indices = np.array([ [2, 1, 3, 4, 5, 6, 7] ,
                    [2, 3, 1, 4, 5, 6, 7] ,
                    [2, 5, 1, 4, 3, 6, 7] ,
                    [2, 5, 7, 4, 3, 6, 1] ,
                    [2, 5, 7, 4, 3, 1, 6] ,
                    [2, 5, 7, 1, 3, 4, 6] ]) -1

In [24]:
for i in range(6):
    ctr = 0
    C = B[:,indices[i]]
    for r in range(7):
        curr = 0
        for c in range(7):
            if curr != C[r,c]:
                ctr += 1
                curr = C[r,c]
    print(i)
    print(ctr)

0
23
1
27
2
19
3
17
4
19
5
15


In [29]:
og, fin = 23, 27
c = 32
a=0.5
ans = np.exp((og-fin)/2)
round(ans,6)

0.135335

In [30]:
B

array([[1, 1, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [34]:
start = np.array([2, 5, 7, 1, 3, 4, 6])-1
C = B[:,start]
print(C)
ctr = 0
for r in range(7):
    curr = 0
    for c in range(7):
        if curr != C[r,c]:
            ctr += 1
            curr = C[r,c]
print(ctr)

[[1 0 0 1 1 1 1]
 [1 1 0 0 0 1 0]
 [0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 1 1 1 1 1 1]
 [0 0 0 0 1 1 1]
 [1 1 1 1 0 0 0]]
15


In [36]:
indices = np.array([[7, 5, 2, 1, 3, 4, 6] ,
                    [2, 7, 5, 1, 3, 4, 6]  ,
                    [5, 2, 7, 1, 3, 4, 6]]) -1
for i in range(len(indices)):
    ctr = 0
    C = B[:,indices[i]]
    for r in range(7):
        curr = 0
        for c in range(7):
            if curr != C[r,c]:
                ctr += 1
                curr = C[r,c]
    print(i)
    print(ctr)

0
15
1
17
2
19


In [38]:
og, fin = 15, 19
c = 32
a=0.5
ans = np.exp((og-fin)/.5)
round(ans,6)

0.000335

In [42]:
pdf = np.ones(20)/20
vals = np.arange(20)+1
np.dot(vals,pdf)

10.5

In [4]:
round(1-binom.cdf(7,10,0.5),6)

0.054688

In [6]:
binom.rvs(100,.5,size=100)

array([41, 54, 47, 49, 55, 51, 45, 54, 43, 45, 52, 52, 56, 53, 54, 48, 53,
       55, 52, 56, 61, 56, 54, 51, 59, 47, 50, 54, 57, 52, 45, 57, 63, 52,
       48, 53, 47, 56, 48, 50, 54, 41, 56, 55, 52, 53, 45, 60, 51, 54, 57,
       49, 52, 47, 49, 50, 43, 56, 54, 57, 52, 55, 48, 47, 57, 55, 53, 50,
       47, 51, 39, 45, 46, 55, 50, 48, 55, 50, 50, 53, 59, 53, 51, 52, 51,
       43, 55, 57, 53, 51, 39, 46, 49, 47, 50, 40, 49, 55, 48, 52])

In [10]:
pdf = np.ones(20)
pdf[0] = 0.5
for i in range(1,20):
    pdf[i] = pdf[i-1]/2
pdf[19] = pdf[19]*2

In [11]:
pdf

array([5.00000000e-01, 2.50000000e-01, 1.25000000e-01, 6.25000000e-02,
       3.12500000e-02, 1.56250000e-02, 7.81250000e-03, 3.90625000e-03,
       1.95312500e-03, 9.76562500e-04, 4.88281250e-04, 2.44140625e-04,
       1.22070312e-04, 6.10351562e-05, 3.05175781e-05, 1.52587891e-05,
       7.62939453e-06, 3.81469727e-06, 1.90734863e-06, 1.90734863e-06])

In [12]:

vals = np.arange(20)+1

1.0

In [13]:
round(.5*.5+.25*.25+.5*.25*2+2*.125*.5,6)

0.6875