# Q2 (b): Dantzig-Wolfe

In [2]:
import numpy as np
from numpy import random
from gurobipy import *

In [3]:
c = np.array([6,5,3,4])
b = np.array([7,17])
A = np.array([[1,1,1,1],
             [2,1,1,3]])
len(A)

2

In [5]:
# Solving the restricted master problem
RMP = Model('RMP')
c = np.array([6,5,3,4])
b = np.array([7,17])
A = np.array([[1,1,1,1],
             [2,1,1,3]])

v = []

# v.append(np.array([1,0,0,0,0,0,0,0,0,1,0,0]))
# v.append(np.array([0,0,0,0,1,0,0,0,0,0,1,0]))
v.append(np.array([0,0,0,0,0,0,0,0,1,0,0,1]))
v.append(np.array([0,0,0,0,0,0,1,1,1,0,0,1]))
# Define Variables
X = []

for i in range(4):
    X.append(RMP.addVar(name='X'+str(i)))

# Define Objective
RMP.setObjective(quicksum(X[i]*c[i] for i in range(len(c))))


# Define Constraints
Constr = {} # indicator constraints
for row in range(len(b)):
    Constr[row] = RMP.addConstr(quicksum(A[row][i]*X[i] for i in range(len(X))),'<=',b[row],name='Constr'+str(row))


#Add constraints and variables to model
RMP.update()
# Initialize Model and Solver Settings NOTE: DO NOT EDIT THE SETTINGS IN THIS BLOCK UNLESS OTHERWISE NOTED IN THE EXERCISE
RMP.setParam('TimeLimit', 900)
RMP.setParam('DualReductions',0)
# ufl.setParam('NodeLimit', 10) # 


RMP.modelSense = GRB.MAXIMIZE
RMP.update()
# Optimize Model (you should see output when running this cell)
RMP.optimize()

Changed value of parameter TimeLimit to 900.0
   Prev: 1e+100  Min: 0.0  Max: 1e+100  Default: 1e+100
Changed value of parameter DualReductions to 0
   Prev: 1  Min: 0  Max: 1  Default: 1
Optimize a model with 2 rows, 4 columns and 8 nonzeros
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [3e+00, 6e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [7e+00, 2e+01]
Presolve time: 0.00s
Presolved: 2 rows, 4 columns, 8 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.8000000e+31   5.750000e+30   1.800000e+01      0s
       1    4.2000000e+01   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.01 seconds
Optimal objective  4.200000000e+01


In [6]:
X

[<gurobi.Var X0 (value 7.0)>,
 <gurobi.Var X1 (value 0.0)>,
 <gurobi.Var X2 (value 0.0)>,
 <gurobi.Var X3 (value 0.0)>]

In [2]:
# ITERATION 1 -NEW
# Solving the restricted master problem
RMP = Model('RMP')
c = np.array([10,1,1,1,10,1,1,1,10,15,15,15])
b = np.array([1,1,1])
# A = np.array([[1,1,1,0,0,0,0,0,0,0,0,0],
#              [0,0,0,1,1,1,0,0,0,0,0,0],
#              [0,0,0,0,0,0,1,1,1,0,0,0]])
A = np.array([1,1,1,1,1,1,1,1,1,0,0,0])

v = []

# v.append(np.array([1,0,0,0,0,0,0,0,0,1,0,0]))
# v.append(np.array([0,0,0,0,1,0,0,0,0,0,1,0]))
v.append(np.array([0,0,0,0,0,0,0,0,1,0,0,1]))
v.append(np.array([0,0,0,0,0,0,1,1,1,0,0,1]))
# Define Variables
alpha = {}

for i in range(len(v)):
    for j in range(len(b)):
        alpha[i,j] = RMP.addVar(lb=-GRB.INFINITY,name='alpha'+str(i))

# Define Objective
RMP.setObjective(quicksum(alpha[i]*quicksum(c[j]*v[i][j] for j in range(len(v[i]))) for i in range(len(v))))


# Define Constraints
Constr = {} # indicator constraints
Constr['alpha'] = RMP.addConstr(quicksum(alpha[i] for i in alpha.keys()),GRB.EQUAL,1,name='Constr_alpha')
Constr['row'] = RMP.addConstr(quicksum(alpha[i]*quicksum(A[j]*v[i][j] for j in range(len(v[i]))) for i in range(len(v))),
                                GRB.EQUAL,1,name='Constr'+str('row'))
# for row in range(1):
#     print(len(v[i]))
#     print(A[0])
#     print(v[0])
#     for i in range(len(v)):
#         print(sum(A[row][j]*v[i][j] for j in range(len(v[i]))))
#     Constr[row] = RMP.addConstr(quicksum(alpha[i]*quicksum(A[row][j]*v[i][j] for j in range(len(v[i]))) for i in range(len(v))),
#                                 GRB.EQUAL,1,name='Constr'+str(row))
#     =======================================================================================


#Add constraints and variables to model
RMP.update()
# Initialize Model and Solver Settings NOTE: DO NOT EDIT THE SETTINGS IN THIS BLOCK UNLESS OTHERWISE NOTED IN THE EXERCISE
RMP.setParam('TimeLimit', 900)
RMP.setParam('DualReductions',0)
# ufl.setParam('NodeLimit', 10) # 


RMP.modelSense = GRB.MINIMIZE
RMP.update()
# Optimize Model (you should see output when running this cell)
RMP.optimize()

Academic license - for non-commercial use only
Changed value of parameter TimeLimit to 900.0
   Prev: 1e+100  Min: 0.0  Max: 1e+100  Default: 1e+100
Changed value of parameter DualReductions to 0
   Prev: 1  Min: 0  Max: 1  Default: 1
Optimize a model with 2 rows, 2 columns and 4 nonzeros
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [3e+01, 3e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 2 rows and 2 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    2.5000000e+01   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective  2.500000000e+01


In [3]:
alpha

{0: <gurobi.Var alpha0 (value 1.0)>, 1: <gurobi.Var alpha1 (value 0.0)>}

In [5]:
# Solving the dual
dual = Model('dual')

# Define Variables
pi = dual.addVar(lb=-GRB.INFINITY, name='pi')
pi_0 = dual.addVar(lb=-GRB.INFINITY, name='pi_0')

# Define Objective
dual.setObjective(pi_0+pi)

rhs = []
for i in range(len(v)):
    rhs.append(sum(c[j]*v[i][j] for j in range(len(v[i]))))

# Define Constraints
Constr = {} # indicator constraints

for i in range(len(v)):
    Constr[i] = dual.addConstr(pi_0+pi*quicksum(A[j]*v[i][j] for j in range(len(v[i]))),
                                '<=',rhs[i],name='Constr'+str(i))

#     =======================================================================================


#Add constraints and variables to model
dual.update()
# Initialize Model and Solver Settings NOTE: DO NOT EDIT THE SETTINGS IN THIS BLOCK UNLESS OTHERWISE NOTED IN THE EXERCISE
dual.setParam('TimeLimit', 900)
dual.setParam('DualReductions',0)
# ufl.setParam('NodeLimit', 10) # 


dual.modelSense = GRB.MAXIMIZE
dual.update()
# Optimize Model (you should see output when running this cell)
dual.optimize()

Changed value of parameter TimeLimit to 900.0
   Prev: 1e+100  Min: 0.0  Max: 1e+100  Default: 1e+100
Changed value of parameter DualReductions to 0
   Prev: 1  Min: 0  Max: 1  Default: 1
Optimize a model with 2 rows, 2 columns and 4 nonzeros
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [3e+01, 3e+01]
Presolve time: 0.00s
Presolved: 2 rows, 2 columns, 4 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0      handle free variables                          0s
       2    2.5000000e+01   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.01 seconds
Optimal objective  2.500000000e+01


In [6]:
pi

<gurobi.Var pi (value 1.0)>

In [7]:
pi_0

<gurobi.Var pi_0 (value 24.0)>

In [9]:
# Calculate c-pi*A
print(c-pi.X*A)

[ 9.  0.  0.  0.  9.  0.  0.  0.  9. 15. 15. 15.]


In [16]:
b

array([ 0,  4,  8,  9, 10, 11], dtype=int64)

In [15]:
a = c-pi.X*A
b = np.where(a>0)[0]
k = [np.power(2,len(b))/2]
while k[-1] > 1:
    k.append(k[-1]/2)
for i in range(np.power(2,len(b))):
    d = np.array([0,0,0,0,0,0,0,0,0,0,0,0])
    for j in range(len(b)):
        if np.floor(i/k[j]) % 2 == 1:
            d[b[j]] = 1
    print(d)
#     v.append(d)

[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1]
[0 0 0 0 0 0 0 0 0 1 1 0]
[0 0 0 0 0 0 0 0 0 1 1 1]
[0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 1]
[0 0 0 0 0 0 0 0 1 0 1 0]
[0 0 0 0 0 0 0 0 1 0 1 1]
[0 0 0 0 0 0 0 0 1 1 0 0]
[0 0 0 0 0 0 0 0 1 1 0 1]
[0 0 0 0 0 0 0 0 1 1 1 0]
[0 0 0 0 0 0 0 0 1 1 1 1]
[0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 1]
[0 0 0 0 1 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 1 1]
[0 0 0 0 1 0 0 0 0 1 0 0]
[0 0 0 0 1 0 0 0 0 1 0 1]
[0 0 0 0 1 0 0 0 0 1 1 0]
[0 0 0 0 1 0 0 0 0 1 1 1]
[0 0 0 0 1 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 0 1 0 0 1]
[0 0 0 0 1 0 0 0 1 0 1 0]
[0 0 0 0 1 0 0 0 1 0 1 1]
[0 0 0 0 1 0 0 0 1 1 0 0]
[0 0 0 0 1 0 0 0 1 1 0 1]
[0 0 0 0 1 0 0 0 1 1 1 0]
[0 0 0 0 1 0 0 0 1 1 1 1]
[1 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 0 0 0 0 1 1]
[1 0 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 0 0 0 0 0 1 0 1]
[1 0 0 0 0 0